package dsa.recursion.leetcode;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 * LeetCode 47 — Permutations II
 * Difficulty: Medium   Tags: Array, Backtracking, Sorting
 * URL: https://leetcode.com/problems/permutations-ii/
 *
 * <h2>Problem</h2>
 * Given a collection of numbers {@code nums} that might contain DUPLICATES,
 * return all possible unique permutations.
 *
 * <h2>Examples</h2>
 * <pre>
 *   [1,1,2]  -> [[1,1,2],[1,2,1],[2,1,1]]
 *   [1,2,3]  -> all 6 permutations
 * </pre>
 *
 * <h2>Approach — sort + skip duplicates rule</h2>
 * Sort the input first. During backtracking, at each level skip a value if it
 * equals the previous AND that previous value is currently NOT in the path
 * (i.e. {@code !used[i-1]}). This ensures each multiset permutation is
 * generated by a unique deterministic path.
 *
 * <h2>Why the {@code !used[i-1]} clause?</h2>
 * If the previous duplicate is still in the path, then picking the current
 * duplicate is genuinely extending the permutation. If the previous was just
 * undone (we backtracked past it), reselecting an equal value at this level
 * would produce a duplicate permutation — skip.
 *
 * Run:
 * <pre>
 *   mvn -pl dsa exec:java -Dexec.mainClass=dsa.recursion.leetcode.LC0047_PermutationsII
 * </pre>
 */
public class LC0047_PermutationsII {

    public static List<List<Integer>> permuteUnique(int[] nums) {
        Arrays.sort(nums);
        List<List<Integer>> out = new ArrayList<>();
        backtrack(nums, new boolean[nums.length], new ArrayList<>(), out);
        return out;
    }

    private static void backtrack(int[] nums, boolean[] used, List<Integer> path, List<List<Integer>> out) {
        if (path.size() == nums.length) { out.add(new ArrayList<>(path)); return; }
        for (int i = 0; i < nums.length; i++) {
            if (used[i]) continue;
            if (i > 0 && nums[i] == nums[i - 1] && !used[i - 1]) continue;
            used[i] = true;
            path.add(nums[i]);
            backtrack(nums, used, path, out);
            path.remove(path.size() - 1);
            used[i] = false;
        }
    }

    public static void main(String[] args) {
        System.out.println(permuteUnique(new int[]{1, 1, 2})); // [[1,1,2],[1,2,1],[2,1,1]]
        System.out.println(permuteUnique(new int[]{1, 2, 3})); // 6 perms
    }
}
